# Generated by Django 5.0.3 on 2024-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todocore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tasks", to="todocore.tag"
            ),
        ),
    ]
