# Generated by Django 5.0.3 on 2024-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todocore", "0002_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
